import {TOPICS,WEEKS,PASS_MASTERY,MIN_MASTERY_ATTEMPTS,generateProblem,topicUnlocked,canTakeExit,updateMastery} from './curriculum.mjs';
import {generateDailyBenchmark,CORE_DAILY_COUNT} from './daily-session.mjs';
const $=id=>document.getElementById(id);const PHASES=['warmup','learn','guided','practice','review','exit'];
const LEVEL_META={standard:{tag:'Level 1 · Standard Practice',emoji:'🟢'},complex:{tag:'Level 2 · Multi-Step Challenge',emoji:'🟡'},word:{tag:'Level 3 · NC Real-World Word Problem',emoji:'🔴'}};
function defaultState(){return{xp:0,total:0,correct:0,streak:0,best:0,mastery:{},attempts:{},cleared:{},day:0,settings:{practiceTarget:10},errorLog:[],sessionStart:0,breakShown:false}}
let S=loadState(),current=0,q=null,exit={left:0,correct:0},bench=null,timer=null;
function loadState(){let parsed;try{parsed=JSON.parse(localStorage.mq7summer||'null')}catch{}const s=parsed||defaultState();s.mastery=s.mastery||{};s.attempts=s.attempts||{};s.cleared=s.cleared||{};s.settings=s.settings||{practiceTarget:10};s.errorLog=s.errorLog||[];for(const t of TOPICS){if(s.mastery[t.id]==null)s.mastery[t.id]=0;if(!s.attempts[t.id])s.attempts[t.id]={n:0,c:0};if(s.cleared[t.id]==null)s.cleared[t.id]=false}return s}
function save(){localStorage.mq7summer=JSON.stringify(S);renderTop()}function renderTop(){$('xp').textContent=S.xp;$('streak').textContent=S.streak}
function go(id){for(const x of ['home','learn','parent'])$(x).classList.toggle('hidden',x!==id);if(id==='home')renderMap()}
async function loadVersion(){try{const r=await fetch('version.json?ts='+Date.now(),{cache:'no-store'}),d=await r.json();$('versionBadge').textContent='v'+d.version}catch{$('versionBadge').textContent='v0.8'}}
function renderMap(){$('weeks').innerHTML=WEEKS.map(w=>`<div class="road"><b>Week ${w.week}: ${w.title}</b><small>${w.standard}</small><p>${w.desc}</p></div>`).join('');$('days').innerHTML=TOPICS.map((t,i)=>{const u=topicUnlocked(S,i),done=S.cleared[t.id]&&S.mastery[t.id]>=PASS_MASTERY;return`<div class="day ${done?'done':''} ${i===S.day?'current':''} ${u?'':'locked'}">${u?t.icon:'🔒'} Day ${i+1}<br><b>${t.title}</b><br>${S.mastery[t.id]}% ${done?'✓':''}</div>`}).join('')}
function continueJourney(){let i=TOPICS.findIndex((t,j)=>topicUnlocked(S,j)&&!S.cleared[t.id]);if(i<0)i=TOPICS.length-1;startLesson(i)}
function startLesson(i){if(!topicUnlocked(S,i))return;current=i;S.day=i;if(!S.sessionStart){S.sessionStart=Date.now();S.breakShown=false}save();go('learn');startClock();showWarmup()}
function startClock(){clearInterval(timer);const tick=()=>{const sec=Math.max(0,Math.floor((Date.now()-S.sessionStart)/1000)),m=Math.floor(sec/60),s=sec%60;$('sessionClock').textContent=`${m}:${String(s).padStart(2,'0')} / 60:00`;if(sec>=1800&&!S.breakShown){S.breakShown=true;save();$('breakModal').classList.remove('hidden')}};tick();timer=setInterval(tick,1000)}
function setPhase(p){for(const x of PHASES)$('p'+x[0].toUpperCase()+x.slice(1)).classList.toggle('on',x===p);$('topicName').textContent=`Day ${current+1}: ${TOPICS[current].title}`;$('masteryPill').textContent=`${S.mastery[TOPICS[current].id]}% mastery`}
function button(label,fn,cls='btn'){const b=document.createElement('button');b.className=cls;b.textContent=label;b.onclick=fn;return b}
function showWarmup(){setPhase('warmup');$('feedback').innerHTML='';$('interaction').innerHTML='';if(current===0){$('lessonBody').innerHTML='<h2>🌞 Day 1 Warm-up</h2><p class="concept">No previous lesson yet. Today starts with the foundations.</p>';$('interaction').append(button('Begin today’s lesson →',showLearn));return}const prev=TOPICS[current-1],w=generateProblem(prev.id);$('lessonBody').innerHTML=`<h2>⚡ Quick Review</h2><p class="concept">Before today’s lesson, recall yesterday’s skill:</p><h3>${w.q}</h3>`;renderAnswers(w,a=>{$('feedback').innerHTML=a===w.a?`<div class="feedback good">✅ Nice recall. ${w.explain}</div>`:`<div class="feedback bad">💡 Review: ${w.explain}</div>`;$('feedback').append(button('Continue to today’s story →',showLearn))})}
function showLearn(){setPhase('learn');const t=TOPICS[current];$('feedback').innerHTML='';$('interaction').innerHTML='';$('lessonBody').innerHTML=`<p class="small">📖 STORY</p><h2>${t.story}</h2>${t.teach}`;$('interaction').append(button('I watched & understand — guided practice →',showGuided))}
function showGuided(){setPhase('guided');const g=TOPICS[current].guided;$('lessonBody').innerHTML=`<h2>🖐️ Guided Practice</h2><p class="concept">${g.prompt}</p><p class="small">Drag a tile into the target, or tap a tile on iPad.</p>`;$('feedback').innerHTML='';$('interaction').innerHTML=`<div class="tokens">${g.tokens.map(x=>`<div class="token" draggable="true" data-v="${esc(x)}">${x}</div>`).join('')}</div><div class="targets"><div id="dropTarget" class="target">DROP / TAP ANSWER</div></div>`;const check=v=>{if(v===g.answer){$('dropTarget').textContent=v;$('feedback').innerHTML=`<div class="feedback good">✨ Correct. ${g.explain}</div><div class="celebrate">⭐ ✅ 🎉</div>`;$('feedback').append(button('Start independent practice →',showPractice))}else{$('feedback').innerHTML=`<div class="feedback bad">🌱 Not yet. ${g.explain} Try again until you make it right.</div><div class="retry">🤔 ↩️ 💡</div>`}};document.querySelectorAll('.token').forEach(el=>{el.onclick=()=>check(el.dataset.v);el.ondragstart=e=>e.dataTransfer.setData('text',el.dataset.v)});$('dropTarget').ondragover=e=>e.preventDefault();$('dropTarget').ondrop=e=>{e.preventDefault();check(e.dataTransfer.getData('text'))}}
function showPractice(){bench={items:generateDailyBenchmark(TOPICS[current].id),idx:0,correct:0,missed:[]};showBenchQuestion()}
function showBenchQuestion(){setPhase('practice');const id=TOPICS[current].id;q=bench.items[bench.idx];const meta=LEVEL_META[q.level],target=S.settings.practiceTarget||'∞';$('lessonBody').innerHTML=`<h2>⚔️ Daily Benchmark — 10 Questions</h2><p class="small">3 standard · 4 multi-step · 3 NC real-world • ✏️ No calculator</p><p class="benchtag ${q.level}">${meta.emoji} ${meta.tag}</p><p class="small">Question ${bench.idx+1} of ${CORE_DAILY_COUNT} • Practice ${S.attempts[id].n}/${target} • Exit needs ≥${PASS_MASTERY}% mastery & ≥${MIN_MASTERY_ATTEMPTS} attempts • Mastery ${S.mastery[id]}%</p>${q.location?`<p class="small">📍 ${esc(q.location)}, NC scenario</p>`:''}<h3 class="qtext">${q.q}</h3>${q.strategy?`<p class="small">🧭 Strategy: ${esc(q.strategy)}</p>`:''}`;$('feedback').innerHTML='';renderAnswers(q,benchCheck)}
function renderAnswers(problem,onPick){$('interaction').innerHTML='<div class="answers"></div>';const box=$('interaction').firstChild;problem.choices.forEach(v=>box.append(button(v,()=>onPick(String(v)),'answer')))}
function benchCheck(v){const id=TOPICS[current].id,a=S.attempts[id],ok=String(v)===String(q.a);a.n++;S.total++;if(ok){a.c++;S.correct++;S.streak++;S.best=Math.max(S.best,S.streak);S.xp+=20;bench.correct++;S.mastery[id]=updateMastery(S.mastery[id],true);$('feedback').innerHTML=`<div class="feedback good">🎉 Correct! ${q.explain} +20 XP</div><div class="celebrate">🌟 🎉 ✅</div>`}else{S.streak=0;S.mastery[id]=updateMastery(S.mastery[id],false);const entry={topic:id,when:new Date().toISOString(),question:q.q,answer:q.a,level:q.level,explain:q.explain};S.errorLog.push(entry);bench.missed.push({number:bench.idx+1,...entry});$('feedback').innerHTML=`<div class="feedback bad">💡 Not yet. Correct answer: ${esc(String(q.a))}. ${q.explain}</div><div class="retry">🧠 🔁</div><p><b>What tripped you up?</b></p><div class="errorOpts"><button data-e="Sign">Sign</button><button data-e="Operation">Operation</button><button data-e="Arithmetic">Arithmetic</button><button data-e="Not sure">Not sure</button></div>`;document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{S.errorLog[S.errorLog.length-1].reason=b.dataset.e;save();b.textContent='Saved ✓'})}save();setPhase('practice');const last=bench.idx>=bench.items.length-1;$('feedback').append(button(last?'See error analysis →':'Next question →',()=>{if(last){benchSummary()}else{bench.idx++;showBenchQuestion()}}))}
function benchSummary(){setPhase('review');const id=TOPICS[current].id,ready=canTakeExit(S,id,S.settings.practiceTarget);const analysis=bench.missed.length?`<h3>🔍 Error Analysis</h3>${bench.missed.map(m=>`<div class="miss"><b>Q${m.number} · ${LEVEL_META[m.level].tag}</b><br>${esc(m.question)}<br><span class="small">✅ Correct answer: ${esc(String(m.answer))} — ${esc(m.explain)}</span></div>`).join('')}`:`<div class="feedback good">🌟 Perfect set! All ${CORE_DAILY_COUNT} correct.</div>`;$('lessonBody').innerHTML=`<h2>🎯 Benchmark Complete</h2><p class="concept">You scored <b>${bench.correct}/${CORE_DAILY_COUNT}</b> on today's 3·4·3 benchmark. Mastery: ${S.mastery[id]}%.</p>${analysis}`;$('interaction').innerHTML='';$('feedback').innerHTML='';if(ready){$('interaction').append(button('Go to Exit Ticket →',startExit));$('interaction').append(button('Another 10-question benchmark',showPractice,'btn alt'))}else{$('interaction').append(button('Start another 10-question benchmark →',showPractice));$('feedback').innerHTML=`<p class="small">Reach ${PASS_MASTERY}% mastery with at least ${MIN_MASTERY_ATTEMPTS} attempts to unlock the Exit Ticket. Review the strategy above and try a fresh benchmark set.</p>`}}
function startExit(){setPhase('exit');exit={left:3,correct:0};nextExitQuestion()}
function nextExitQuestion(){if(exit.left<=0)return finishExit();q=generateProblem(TOPICS[current].id);$('lessonBody').innerHTML=`<div class="exit"><h2>🎫 Exit Ticket</h2><p>Question ${4-exit.left} of 3</p><p class="concept">${q.q}</p></div>`;$('feedback').innerHTML='';renderAnswers(q,v=>{const ok=String(v)===String(q.a);if(ok)exit.correct++;exit.left--;$('feedback').innerHTML=ok?`<div class="feedback good">✅ Correct. ${q.explain}</div>`:`<div class="feedback bad">💡 ${q.explain}</div>`;$('feedback').append(button(exit.left?'Next Exit Question →':'Finish Exit Ticket →',nextExitQuestion))})}
function finishExit(){const id=TOPICS[current].id,passed=exit.correct>=2&&S.mastery[id]>=PASS_MASTERY;if(passed){S.cleared[id]=true;S.xp+=50;save();setPhase('review');$('lessonBody').innerHTML=`<h2>🏆 Day ${current+1} Cleared!</h2><p class="concept">Exit Ticket: ${exit.correct}/3. Mastery: ${S.mastery[id]}%.</p><p>You unlocked the next learning day. Older concepts will return in future warm-ups.</p><div class="celebrate">🏆 ⭐ 🎉</div>`;$('interaction').innerHTML='';$('feedback').innerHTML='';$('interaction').append(button(current<TOPICS.length-1?'Return to roadmap →':'Enter Endless Mastery →',()=>{S.sessionStart=0;save();go('home')}));$('interaction').append(button('Extra practice on this skill',showPractice,'btn alt'))}else{$('lessonBody').innerHTML=`<h2>🔁 Review Loop</h2><p class="concept">Exit Ticket: ${exit.correct}/3. Mastery: ${S.mastery[id]}%.</p><p>You need at least 2 of 3 on the exit ticket and ${PASS_MASTERY}% mastery. We’ll loop back through practice instead of unlocking too soon.</p>`;$('interaction').innerHTML='';$('feedback').innerHTML='';$('interaction').append(button('Practice, then retry Exit Ticket →',showPractice))}}
function openParent(){go('parent');$('parentLock').classList.remove('hidden');$('dashboard').classList.add('hidden');$('pinIntro').textContent=localStorage.mq7ParentPin?'Enter your 4-digit parent PIN.':'Create a 4-digit parent PIN for this device.';$('practiceTarget').value=String(S.settings.practiceTarget)}
function parentAuth(){const p=$('parentPin').value.trim();if(!/^\d{4}$/.test(p))return $('pinMsg').textContent='Use exactly 4 digits.';if(!localStorage.mq7ParentPin)localStorage.mq7ParentPin=p;if(p!==localStorage.mq7ParentPin)return $('pinMsg').textContent='Incorrect PIN.';$('parentLock').classList.add('hidden');$('dashboard').classList.remove('hidden');renderDashboard()}
function renderDashboard(){$('dXp').textContent=S.xp;$('dSolved').textContent=S.total;$('dAcc').textContent=(S.total?Math.round(S.correct/S.total*100):0)+'%';$('dBest').textContent=S.best;$('skills').innerHTML=TOPICS.map((t,i)=>`<p><b>${t.icon} Day ${i+1}: ${t.title}</b> — ${S.mastery[t.id]}% ${S.cleared[t.id]?'✓ Cleared':''}</p><div class="bar"><i style="width:${S.mastery[t.id]}%"></i></div>`).join('')}
function exportProgress(){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mathquest7-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function changePin(){const p=prompt('New 4-digit parent PIN');if(/^\d{4}$/.test(p)){localStorage.mq7ParentPin=p;alert('PIN updated.')}else if(p!==null)alert('PIN must be exactly 4 digits.')}
function resetLearning(){if(confirm('Reset learning progress but keep parent PIN and practice settings?')){const settings=S.settings;S=defaultState();S.settings=settings;save();location.reload()}}
async function clearAll(){if(!confirm('Clear ALL MathQuest data from this browser/device? This cannot be undone.'))return;Object.keys(localStorage).filter(k=>k.toLowerCase().startsWith('mq7')||k.toLowerCase().includes('mathquest')).forEach(k=>localStorage.removeItem(k));if('caches'in window)for(const k of await caches.keys())if(k.toLowerCase().includes('mathquest'))await caches.delete(k);alert('All MathQuest local data cleared.');location.reload()}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
$('continueBtn').onclick=continueJourney;$('parentBtn').onclick=openParent;$('mapBtn').onclick=()=>go('home');$('studentBtn').onclick=()=>go('home');$('pinOpen').onclick=parentAuth;$('practiceTarget').onchange=e=>{S.settings.practiceTarget=Number(e.target.value);save()};$('exportBtn').onclick=exportProgress;$('changePinBtn').onclick=changePin;$('resetBtn').onclick=resetLearning;$('clearBtn').onclick=clearAll;$('breakContinue').onclick=()=>$('breakModal').classList.add('hidden');renderTop();renderMap();loadVersion();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
